window.GENKI_STARTER_LESSONS = [
  {
    lessonNumber: "3",
    pageNumber: "84",
    entries: [
      { japanese: "映画", translation: "movie" },
      { japanese: "音楽", translation: "music" },
      { japanese: "雑誌", translation: "magazine" },
      { japanese: "お酒", translation: "sake" },
      { japanese: "お茶", translation: "tea" },
      { japanese: "水", translation: "water" },
      { japanese: "朝ご飯", translation: "breakfast" },
      { japanese: "昼ご飯", romaji: "hirugohan", translation: "lunch = noon + meal" },
      { japanese: "晩ご飯", romaji: "bangohan", translation: "dinner = night + meal" },
      { japanese: "家", translation: "house / home" },
      { japanese: "学校", translation: "school" },
      { japanese: "明日", translation: "tomorrow" },
      { japanese: "今日", translation: "today" },
      { japanese: "朝", translation: "morning" },
      { japanese: "今晩", romaji: "konban", translation: "tonight = now + night" },
      { japanese: "毎日", translation: "every day" },
      { japanese: "毎晩", romaji: "manban", translation: "every night = every + night" },
      { japanese: "週末", translation: "weekend" },
      { japanese: "土曜日", romaji: "doyoubi", translation: "saturday = dirt + weekday" },
      { japanese: "日曜日", romaji: "nichiyoubi", translation: "sunday = sun + weekday" },
      { japanese: "行く", translation: "to go" },
      { japanese: "帰る", translation: "to return" },
      { japanese: "聞く", translation: "to hear" },
      { japanese: "飲む", translation: "to drink" },
      { japanese: "話す", translation: "to talk" },
      { japanese: "読む", translation: "to read" },
      { japanese: "起きる", translation: "to wake up" },
      { japanese: "食べる", translation: "to eat" },
      { japanese: "寝る", romaji: "neru", translation: "to sleep" },
      { japanese: "見る", translation: "to see" },
      { japanese: "来る", translation: "to come" },
      { japanese: "勉強する", romaji: "benkyousuru", translation: "to study" },
      { japanese: "早い", translation: "early / fast" },
      { japanese: "全然", romaji: "zenzen", translation: "not at all / entirely = all + nature" },
      { japanese: "時々", translation: "sometimes" },
    ],
  },
  {
    lessonNumber: "4",
    pageNumber: "104",
    entries: [
      { japanese: "買い物", translation: "shopping" },
      { japanese: "犬", translation: "dog" },
      { japanese: "猫", translation: "cat" },
      { japanese: "人", translation: "person" },
      { japanese: "子供", romaji: "kodomo", translation: "child" },
      { japanese: "机", romaji: "tsukue", translation: "table" },
      { japanese: "写真", romaji: "shya-shin", translation: "photo / picture" },
      { japanese: "花", translation: "flower" },
      { japanese: "ご飯", translation: "meal" },
      { japanese: "お寺", translation: "temple" },
      { japanese: "公園", translation: "garden" },
      { japanese: "バス停", translation: "bus stop" },
      { japanese: "病院", translation: "hospital" },
      { japanese: "本屋", translation: "bookstore" },
      { japanese: "町", translation: "town" },
      { japanese: "昨日", translation: "yesterday" },
      { japanese: "時間", translation: "hours" },
      { japanese: "一時間", translation: "1 hour" },
      { japanese: "先週", translation: "last week" },
      { japanese: "時", translation: "time / when" },
      { japanese: "月曜日", translation: "monday" },
      { japanese: "火曜日", translation: "tuesday" },
      { japanese: "水曜日", translation: "wednesday" },
      { japanese: "木曜日", translation: "thursday" },
      { japanese: "金曜日", translation: "friday" },
      { japanese: "会う", translation: "to meet" },
      { japanese: "買う", translation: "to buy" },
      { japanese: "書く", translation: "to write" },
      { japanese: "撮る", translation: "to take a picture / to photograph" },
      { japanese: "待つ", translation: "to wait" },
      { japanese: "一人で", translation: "alone" },
      { japanese: "右", translation: "right" },
      { japanese: "左", translation: "left" },
      { japanese: "前", translation: "in front" },
      { japanese: "後ろ", translation: "back" },
      { japanese: "中", translation: "inside" },
      { japanese: "上", translation: "on / up" },
      { japanese: "下", translation: "under / below" },
      { japanese: "近く", translation: "near" },
      { japanese: "隣", translation: "next to" },
      { japanese: "間", translation: "between / interval" },
    ],
  },
  {
    lessonNumber: "5",
    pageNumber: "130",
    entries: [
      { japanese: "食べ物", romaji: "tabemono", translation: "food / meal" },
      { japanese: "飲み物", romaji: "nomimono", translation: "drink / beverage" },
      { japanese: "果物", romaji: "kudamono", translation: "fruit" },
      { japanese: "休み", romaji: "yasumi", translation: "holiday / rest / absence" },
      { japanese: "旅行", romaji: "ryokou", translation: "travel / trip" },
      { japanese: "お土産", romaji: "omiyage", translation: "souvenir" },
      { japanese: "天気", romaji: "tenki", translation: "weather" },
      { japanese: "宿題", romaji: "shyukudai", translation: "homework" },
      { japanese: "誕生日", romaji: "tanjyoubi", translation: "birthday" },
      { japanese: "僕", romaji: "boku", translation: "I (man)" },
      { japanese: "新しい", romaji: "atarashii", translation: "new" },
      { japanese: "古い", romaji: "furui", translation: "old" },
      { japanese: "暑い", romaji: "atsui", translation: "hot (weather)" },
      { japanese: "寒い", romaji: "samui", translation: "cold (weather)" },
      { japanese: "忙しい", romaji: "isogashii", translation: "busy" },
      { japanese: "大きい", romaji: "ookii", translation: "big" },
      { japanese: "小さい", romaji: "chiisai", translation: "small" },
      { japanese: "面白い", romaji: "omoshiroi", translation: "interesting / funny / amusing" },
      { japanese: "つまらない", translation: "boring" },
      { japanese: "やさしい", translation: "easy (problem) / kind (person)" },
      { japanese: "難しい", romaji: "muzukashii", translation: "difficult" },
      { japanese: "かっこいい", translation: "good-looking" },
      { japanese: "怖い", romaji: "kowai", translation: "frightening / scary" },
      { japanese: "楽しい", romaji: "tanoshii", translation: "fun" },
      { japanese: "安い", romaji: "yasui", translation: "cheap" },
      { japanese: "好き", romaji: "suki", translation: "like / love" },
      { japanese: "嫌い", romaji: "kirai", translation: "dislike" },
      { japanese: "大好き", romaji: "daisuki", translation: "like / love very much" },
      { japanese: "大嫌い", romaji: "daikirai", translation: "hate" },
      { japanese: "きれい", translation: "beautiful" },
      { japanese: "元気", romaji: "genki", translation: "healthy / energetic" },
      { japanese: "静か", romaji: "shizuka", translation: "quiet" },
      { japanese: "にぎやか", translation: "lively / busy" },
      { japanese: "暇", romaji: "hima", translation: "free" },
      { japanese: "泳ぐ", romaji: "oyogu", translation: "to swim" },
      { japanese: "聞く", romaji: "kiku", translation: "to ask" },
      { japanese: "乗る", romaji: "noru", translation: "to ride" },
      { japanese: "やる", translation: "to do" },
      { japanese: "出かける", romaji: "dekakeru", translation: "to go out" },
      { japanese: "一緒に", romaji: "isshyani", translation: "together" },
      { japanese: "すごく", translation: "extremely" },
      { japanese: "大丈夫", romaji: "daijyoubu", translation: "it's all right" },
    ],
  },
  {
    lessonNumber: "6",
    pageNumber: "148",
    entries: [
      { japanese: "漢字", romaji: "kanji", translation: "kanji" },
      { japanese: "教科書", romaji: "kyou-ka-shyou", translation: "textbook" },
      { japanese: "ページ", translation: "page" },
      { japanese: "次", romaji: "tsugi", translation: "next" },
      { japanese: "お金", romaji: "okane", translation: "money" },
      { japanese: "荷物", romaji: "nimotsu", translation: "luggage / baggage" },
      { japanese: "パソコン", translation: "PC" },
      { japanese: "シャワー", translation: "shower" },
      { japanese: "電気", romaji: "denki", translation: "electricity / light" },
      { japanese: "窓", romaji: "mado", translation: "window" },
      { japanese: "電車", romaji: "denshya", translation: "train" },
      { japanese: "国", romaji: "kuni", translation: "country" },
      { japanese: "今週", romaji: "konshyu", translation: "this week" },
      { japanese: "来週", romaji: "raishyu", translation: "next week" },
      { japanese: "来年", romaji: "rainen", translation: "next year" },
      { japanese: "夜", romaji: "yoru", translation: "night" },
      { japanese: "大変", romaji: "taihen", translation: "tough / serious / difficult" },
      { japanese: "遊ぶ", romaji: "asobu", translation: "to play" },
      { japanese: "急ぐ", romaji: "isogu", translation: "to hurry" },
      { japanese: "返す", romaji: "kaesu", translation: "to return" },
      { japanese: "消す", romaji: "kesu", translation: "to turn off" },
      { japanese: "死ぬ", romaji: "shinu", translation: "to die" },
      { japanese: "座る", romaji: "suwaru", translation: "to sit" },
      { japanese: "立つ", romaji: "tatsu", translation: "to stand up" },
      { japanese: "たばこを吸う", romaji: "tabako o suu", translation: "to smoke" },
      { japanese: "使う", romaji: "tsukau", translation: "to use" },
      { japanese: "手伝う", romaji: "tetsudau", translation: "to help" },
      { japanese: "入る", romaji: "hairu", translation: "to enter" },
      { japanese: "持つ", romaji: "motsu", translation: "to bring" },
      { japanese: "休む", romaji: "yasumu", translation: "to rest / to be absent" },
      { japanese: "開ける", romaji: "akeru", translation: "to open" },
      { japanese: "閉める", romaji: "shimeru", translation: "to close" },
      { japanese: "教える", romaji: "oshieru", translation: "to teach" },
      { japanese: "忘れる", romaji: "wasureru", translation: "to forget" },
      { japanese: "降りる", romaji: "oriru", translation: "to get off" },
      { japanese: "借りる", romaji: "kariru", translation: "to borrow" },
      { japanese: "つける", romaji: "tsukeru", translation: "to turn on" },
      { japanese: "電話する", romaji: "denwasuru", translation: "to call" },
      { japanese: "連れてくる", romaji: "tsuretekuru", translation: "to bring (a person)" },
      { japanese: "持ってくる", romaji: "mottekuru", translation: "to bring (a thing)" },
      { japanese: "後で", romaji: "atode", translation: "after" },
      { japanese: "すぐ", romaji: "sugu", translation: "right now" },
      { japanese: "ゆっくり", translation: "slowly" },
      { japanese: "結構です", romaji: "kekkou desu", translation: "No, thank you" },
      { japanese: "本当ですか", romaji: "hontou desuka", translation: "are you sure / really" },
    ],
  },
];
